
{{- $refreshPeriod := "168h" }}

["cht.sh"]
	type = "file"
	url = "https://cht.sh/:cht.sh"
  refreshPeriod = "{{ $refreshPeriod }}"
  executable = true

{{ if .toolchains.rust -}}
[rustup-init]
    type = "file"
    url = "https://sh.rustup.rs"
    refreshPeriod = "{{ $refreshPeriod }}"
    executable = true
{{- end -}}
