{{- $refreshPeriod := "168h" }}

[asdf]
  type = "archive-file"
  url = {{ gitHubLatestReleaseAssetURL "asdf-vm/asdf" (printf "asdf-*-%s-%s.tar.gz" .chezmoi.os .chezmoi.arch) | quote }}
  path = "asdf"
  refreshPeriod = "{{ $refreshPeriod }}"
  executable = true

{{ if .toolchains.rust -}}
[rustup-init]
    type = "file"
    url = "https://sh.rustup.rs"
    refreshPeriod = "{{ $refreshPeriod }}"
    executable = true
{{- end -}}
