[packages.os.darwin.cloud]
aws = {disabled = "headless", manager = "system", package = "awscli"}

[packages.os.darwin.core]
age-plugin-yubikey = {}
atuin = {manager = "system"}
coreutils = {version = "grealpath --version"}
difftastic = {manager = "system"}
doggo = {manager = "system"}
dust = {manager = "system"}
eza = {manager = "system"}
glow = {manager = "system"}
hyperfine = {manager = "system"}
jnv = {manager = "system"}
lazygit = {manager = "system"}
mas = {version = "mas version"}
mkcert = {manager = "system"}
openssh-client = {package = "openssh", test = "test -x $HOMEBREW_PREFIX/bin/ssh && test -x $HOMEBREW_PREFIX/bin/ssh-agent && test -x $HOMEBREW_PREFIX/bin/ssh-add"}
ouch = {manager = "system"}
"pinentry-mac" = {}
rage = {manager = "system"}
sd = {manager = "system"}
topgrade = {manager = "system"}
vivid = {manager = "system"}
xh = {manager = "system"}
yazi = {manager = "system"}

[packages.os.darwin.docker]
dive = {manager = "system"}

[packages.os.darwin.extra]
gocryptfs = {package = "gromgit/fuse/gocryptfs-mac"}
opensc = {bin = "opensc-tool"}
pam-u2f = {bin = "pamu2fcfg"}
ykman = {}

[packages.os.darwin.iac]
sops = {manager = "system"}
terragrunt = {manager = "system"}

[packages.os.darwin.kubernetes]
helm = {manager = "system"}
k3d = {manager = "system"}
k9s = {manager = "system"}
kubecolor = {manager = "system"}
kubectl = {manager = "system", package = "kubernetes-cli"}
kustomize = {manager = "system"}
oc = {manager = "system", package = "openshift-cli"}
stern = {manager = "system"}
yq = {manager = "system"}
