[packages.os.darwin.ai]
llamacpp = { bin = "llama-server", manager = "brew", package = "adyranov/tap/llama-cpp" }
omlx = { exclude_arch = ["amd64"], manager = "system", package = "jundot/omlx/omlx" }

[packages.os.darwin.cloud]
aws = { disabled = ["headless"] }

[packages.os.darwin.core]
age-plugin-yubikey = {}
atuin = { manager = "system" }
coreutils = { version = "grealpath --version" }
gnupg = { package = "gnupg2" }
mas = { manager = "brew", version = "mas version" }
openssh-client = { exclude_arch = ["arm64"], package = "openssh +fido2", test = "command -v ssh && command -v ssh-agent && command -v ssh-add" }
openssh-client-arm64 = { bin = "ssh", exclude_arch = ["amd64"], manager = "brew", package = "openssh", test = "command -v ssh && command -v ssh-agent && command -v ssh-add" }

[packages.os.darwin.docker]
docker-buildx = { package = "docker-buildx-plugin" }
docker-compose = { package = "docker-compose-plugin" }

[packages.os.darwin.extra]
gocryptfs = { package = "gocryptfs" }
opensc = { bin = "opensc-tool" }
pam-u2f = { bin = "pamu2fcfg" }
ykman = { package = "yubikey-manager" }
