# syntax=docker/dockerfile:1.4

FROM ubuntu:jammy

ARG USER=devcontainer
ARG UID=54321

ENV HOME=/home/$USER

WORKDIR $HOME

RUN set -eux \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
              apt-transport-https \
              bash \
              ca-certificates \
              curl \
              dialog \
              dirmngr \
              gnupg \
              htop \
              init-system-helpers \
              iproute2 \
              jq \
              less \
              libc6 \
              libgcc1 \
              libgssapi-krb5-2 \
              libicu[0-9][0-9] \
              libkrb5-3 \
              liblttng-ust1 \
              libstdc++6 \
              locales \
              lsb-release \
              lsof \
              man-db \
              manpages \
              manpages-dev \
              nano \
              ncdu \
              netbase \
              net-tools \
              openssh-client \
              procps \
              psmisc \
              rsync \
              strace \
              sudo \
              tzdata \
              unzip \
              vim-tiny \
              wget \
              zip \
              zlib1g \
              zsh \
    && echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
    && locale-gen \
    && groupadd --gid $UID $USER \
    && useradd -s $(which zsh) --uid $UID --gid $USER -m $USER \
    && echo "$USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USER \
    && chmod 0440 /etc/sudoers.d/$USER \
    && chown -R $USER:$USER $HOME \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/* /var/log/* /tmp/*

USER $USER

COPY --chown=$USER:$USER . .local/share/chezmoi

RUN --mount=type=secret,id=GITHUB_TOKEN,dst=/run/secrets/github_token,uid=$UID \
    GITHUB_API_TOKEN=$(cat /run/secrets/github_token) .local/share/chezmoi/install.sh --exclude=scripts \
    && sudo rm -rf /var/lib/apt/lists/* /var/cache/apt/* /var/log/* /tmp/*

RUN --mount=type=secret,id=GITHUB_TOKEN,dst=/run/secrets/github_token,uid=$UID \
    GITHUB_API_TOKEN=$(cat /run/secrets/github_token) .local/bin/install-system-packages \
    && sudo rm -rf /var/lib/apt/lists/* /var/cache/apt/* /var/log/* /tmp/*

RUN --mount=type=secret,id=GITHUB_TOKEN,dst=/run/secrets/github_token,uid=$UID \
    GITHUB_API_TOKEN=$(cat /run/secrets/github_token) .local/bin/install-asdf-packages \
    && sudo rm -rf /var/lib/apt/lists/* /var/cache/apt/* /var/log/* /tmp/*

RUN --mount=type=secret,id=GITHUB_TOKEN,dst=/run/secrets/github_token,uid=$UID \
    GITHUB_API_TOKEN=$(cat /run/secrets/github_token) .local/bin/install-helm-plugins \
    && sudo rm -rf /var/lib/apt/lists/* /var/cache/apt/* /var/log/* /tmp/*

RUN --mount=type=secret,id=GITHUB_TOKEN,dst=/run/secrets/github_token,uid=$UID \
    GITHUB_API_TOKEN=$(cat /run/secrets/github_token) .local/bin/install-krew-plugins \
    && sudo rm -rf /var/lib/apt/lists/* /var/cache/apt/* /var/log/* /tmp/*

RUN --mount=type=secret,id=GITHUB_TOKEN,dst=/run/secrets/github_token,uid=$UID \
    GITHUB_API_TOKEN=$(cat /run/secrets/github_token) .local/share/chezmoi/install.sh \
    && ~/.local/share/chezmoi/test/run_tests.sh \
    && sudo rm -rf /var/lib/apt/lists/* /var/cache/apt/* /var/log/* /tmp/*

CMD /bin/zsh
