# syntax=docker/dockerfile:1.3

FROM alpine:edge

ARG USER=devcontainer
ARG UID=54321

ENV HOME=/home/$USER

WORKDIR $HOME

COPY . .local/share/chezmoi

RUN apk add --update \
        bash \
        ca-certificates \
        coreutils \
        curl \
        doas \
        git \
        gnupg \
        grep \
        htop \
        jq \
        krb5-libs \
        less \
        libgcc \
        libintl \
        libssl1.1 \
        libstdc++ \
        lsof \
        lttng-ust \
        man-pages \
        mandoc \
        nano \
        ncdu \
        ncurses \
        net-tools \
        openssh-client \
        procps \
        psmisc \
        rsync \
        sed \
        shadow \
        strace \
        tzdata \
        unzip \
        userspace-rcu \
        vim \
        wget \
        which \
        zip \
        zlib \
        zsh \
    && adduser -u $UID -s $(which zsh) -D $USER \
    && echo "permit nopass $USER as root" > /etc/doas.d/doas.conf \
    && chown -R $USER:$USER $HOME \
    && rm -rf /var/cache/apk/* /tmp/*

USER $USER

RUN --mount=type=secret,id=GITHUB_TOKEN,dst=/run/secrets/github_token \
    GITHUB_API_TOKEN=$(cat /run/secrets/github_token) .local/share/chezmoi/install.sh --exclude=scripts \
    && doas rm -rf /var/cache/apk/* /tmp/*

RUN --mount=type=secret,id=GITHUB_TOKEN,dst=/run/secrets/github_token \
    GITHUB_API_TOKEN=$(cat /run/secrets/github_token) .local/bin/install-system-packages \
    && doas rm -rf /var/cache/apk/* /tmp/*

RUN --mount=type=secret,id=GITHUB_TOKEN,dst=/run/secrets/github_token \
    GITHUB_API_TOKEN=$(cat /run/secrets/github_token) .local/bin/install-asdf-packages \
    && doas rm -rf /var/cache/apk/* /tmp/*

RUN --mount=type=secret,id=GITHUB_TOKEN,dst=/run/secrets/github_token \
    GITHUB_API_TOKEN=$(cat /run/secrets/github_token) .local/bin/install-helm-plugins \
    && doas rm -rf /var/cache/apk/* /tmp/*

RUN --mount=type=secret,id=GITHUB_TOKEN,dst=/run/secrets/github_token \
    GITHUB_API_TOKEN=$(cat /run/secrets/github_token) .local/bin/install-krew-plugins \
    && doas rm -rf /var/cache/apk/* /tmp/*

RUN --mount=type=secret,id=GITHUB_TOKEN,dst=/run/secrets/github_token \
    GITHUB_API_TOKEN=$(cat /run/secrets/github_token) .local/share/chezmoi/install.sh \
    && doas rm -rf /var/cache/apk/* /tmp/*

CMD /bin/zsh
