essentials:
  - name: "bash"
  - name: "coreutils"
  - name: "curl"
  - name: "git"
  - name: "gnupg"
  - name: "jq"
  - name: "wget"
  - name: "zsh"
packages:
  - name: "bat"
  - { name: "colima", no-ubuntu: true, no-alpine: true }
  - { name: "datree", no-ubuntu: true, no-alpine: true, asdfVersion: "latest" }
  - { name: "delta", darwin: "git-delta", no-ubuntu: true, asdfVersion: "latest" }
  - { name: "direnv", no-darwin: true, no-ubuntu: true, no-alpine: true, asdfVersion: "latest" }
  - { name: "dive", no-ubuntu: true, no-alpine: true, asdfVersion: "latest" }
  - { name: "docker", ubuntu: "moby-cli", alpine: "docker-cli" }
  - name: "exa"
  - { name: "fd", ubuntu: "fd-find" }
  - { name: "gh", no-ubuntu: true, alpine: "github-cli", asdf: "github-cli", asdfVersion: "latest" }
  - { name: "helm", no-alpine: true, asdfVersion: "latest" }
  - name: "htop"
  - { name: "httpie", test: "http --version" }
  - { name: "java", no-darwin: true, no-ubuntu: true, alpine: "openjdk17-jdk", asdfVersion: "latest:temurin-17" }
  - { name: "k9s", no-ubuntu: true, no-alpine: true, asdfVersion: "latest" }
  - { name: "kubectl", no-alpine: true, asdfVersion: "latest" }
  - { name: "kubectx", no-ubuntu: true, asdfVersion: "latest" }
  - { name: "mas", no-ubuntu: true, no-alpine: true, test: "mas" }
  - { name: "maven", no-darwin: true, no-ubuntu: true, asdfVersion: "3.8.6", test: "mvn --help" }
  - { name: "neovim", test: "nvim --help" }
  - { name: "nodejs", no-darwin: true, asdfVersion: "latest:18", test: "node --help" }
  - { name: "npm", no-darwin: true, no-ubuntu: true, test: "npm -v" }
  - { name: "popeye", no-ubuntu: true, no-alpine: true, asdfVersion: "v0.10.1" }
  - { name: "pre-commit", no-ubuntu: true, no-alpine: true, asdfVersion: "latest" }
  - { name: "ripgrep", test: "rg --help" }
  - name: "skopeo"
  - { name: "sops", no-ubuntu: true, no-alpine: true, asdfVersion: "latest" }
  - { name: "stern", no-ubuntu: true, no-alpine: true, asdfVersion: "latest" }
  - { name: "terraform", no-ubuntu: true, no-alpine: true, asdfVersion: "latest" }
  - { name: "terragrunt", no-ubuntu: true, no-alpine: true, asdfVersion: "latest" }
  - { name: "tflint", no-ubuntu: true, no-alpine: true, asdfVersion: "latest" }
  - { name: "tmux", test: "tmux -V" }
  - name: "yarn"
  - { name: "yq", no-ubuntu: true, asdfVersion: "latest" }
asdf:
  plugins:
    - name: "datree"
      url: "https://github.com/webofmars/asdf-plugin-datree"
apt:
  repositories:
    - name: "microsoft"
      key: "https://packages.microsoft.com/keys/microsoft.asc"
      string: "deb https://packages.microsoft.com/ubuntu/$(lsb_release -rs)/prod $(lsb_release -cs) main"
    - name: "git-core-ubuntu-ppa"
      key: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xe1dd270288b4e6030699e45fa1715d88e1df1f24"
      string: "deb http://ppa.launchpad.net/git-core/ppa/ubuntu $(lsb_release -cs) main"
    - name: "helm-stable-debian"
      key: "https://baltocdn.com/helm/signing.asc"
      string: "deb https://baltocdn.com/helm/stable/debian all main"
    - name: "kubernetes"
      key: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
      string: "deb https://apt.kubernetes.io kubernetes-xenial main"
    - name: "kubic-libcontainers-stable"
      key: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_$(lsb_release -rs)/Release.key"
      string: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_$(lsb_release -rs)/ /"
    - name: "nodesource"
      key: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
      string: "deb https://deb.nodesource.com/node_18.x $(lsb_release -cs) main"
    - name: "yarn"
      key: "https://dl.yarnpkg.com/debian/pubkey.gpg"
      string: "deb https://dl.yarnpkg.com/debian/ stable main"

brew:
  taps:
    - name: "homebrew/autoupdate"
    - name: "homebrew/bundle"
    - name: "homebrew/cask"
    - name: "homebrew/cask-fonts"
    - name: "homebrew/cask-versions"
    - name: "homebrew/command-not-found"
    - name: "homebrew/core"
    - name: "datreeio/datree"
  casks:
    - name: "authy"
    - name: "brave-browser"
    - name: "calibre"
    - name: "cinebench"
    - name: "discord"
    - name: "dropbox"
    - name: "firefox"
    - name: "font-fira-code"
    - name: "geekbench"
    - name: "google-chrome"
    - name: "google-drive"
    - name: "gpg-suite"
    - name: "handbrake"
    - name: "iterm2"
    - name: "jetbrains-toolbox"
    - name: "lens"
    - name: "macfuse"
    - name: "microsoft-edge"
    - name: "private-internet-access"
    - name: "qbittorrent"
    - name: "rectangle"
    - name: "skype"
    - name: "spotify"
    - name: "teamviewer"
    - name: "telegram-desktop"
    - name: "tor-browser"
    - name: "visual-studio-code"
    - name: "vlc"
    - name: "xnviewmp"
    - name: "yandex-disk"
    - name: "zoom"
  apps:
    - name: "Brother iPrint&Scan"
      id: "1193539993"
    - name: "Disk Speed Test"
      id: "425264550"
    - name: "Grammarly for Safari"
      id: "1462114288"
    - name: "Messenger"
      id: "1480068668"
    - name: "Slack"
      id: "803453959"
    - name: "The Unarchiver"
      id: "425424353"
helm:
  plugins:
    - name: "diff"
      url: "https://github.com/databus23/helm-diff"
    - name: "secrets"
      url: "https://github.com/jkroepke/helm-secrets"
krew:
  plugins:
    - { name: "access-matrix", linux_arm64: "no" }
    - { name: "datree", test: "version" }
    - { name: "deprecations", linux_arm64: "no" }
    - { name: "get-all", linux_arm64: "no" }
    - name: "konfig"
    - { name: "modify-secret", linux_arm64: "no" }
    - name: "neat"
    - { name: "node-shell", test: "-v" }
    - name: "resource-capacity"
    - name: "score"
    - { name: "sniff", alpine: "no", linux_arm64: "no" }
    - { name: "tree", linux_arm64: "no" }
    - name: "tunnel"
    - { name: "view-allocations", alpine: "no", linux_arm64: "no" }
    - name: "who-can"
