packages:
  - name: "bash"
  - name: "bat"
  - { name: "colima", no-apt: true, no-apk: true }
  - name: "curl"
  - { name: "datree", no-apt: true, no-apk: true, asdfVersion: "latest" }
  - { name: "delta", brew: "git-delta", no-apt: true, asdfVersion: "latest" }
  - { name: "direnv", no-brew: true, no-apt: true, no-apk: true, asdfVersion: "latest" }
  - { name: "dive", no-apt: true, no-apk: true, asdfVersion: "latest" }
  - { name: "docker", apt: "moby-cli", apk: "docker-cli" }
  - name: "exa"
  - { name: "fd", apt: "fd-find" }
  - { name: "gh", no-apt: true, apk: "github-cli", asdf: "github-cli", asdfVersion: "latest" }
  - name: "git"
  - name: "gnupg"
  - { name: "helm", no-apk: true, asdfVersion: "latest" }
  - name: "htop"
  - name: "httpie"
  - { name: "java", no-brew: true, no-apt: true, apk: "openjdk17-jdk", asdfVersion: "latest:temurin-17" }
  - name: "jq"
  - { name: "k9s", no-apt: true, no-apk: true, asdfVersion: "latest" }
  - { name: "kubectl", no-apk: true, asdfVersion: "latest" }
  - { name: "kubectx", no-apt: true, asdfVersion: "latest" }
  - { name: "mas", no-apt: true, no-apk: true }
  - { name: "maven", no-brew: true, no-apt: true, asdfVersion: "3.8.6" }
  - name: "neovim"
  - { name: "nodejs", brew: "node@18" }
  - { name: "npm", no-brew: true, no-apt: true }
  - { name: "popeye", no-apt: true, no-apk: true, asdfVersion: "v0.10.1" }
  - { name: "pre-commit", no-apt: true, no-apk: true, asdfVersion: "latest" }
  - name: "ripgrep"
  - name: "skopeo"
  - { name: "sops", no-apt: true, no-apk: true, asdfVersion: "latest" }
  - { name: "stern", no-apt: true, no-apk: true, asdfVersion: "latest" }
  - { name: "terraform", no-apt: true, no-apk: true, asdfVersion: "latest" }
  - { name: "terragrunt", no-apt: true, no-apk: true, asdfVersion: "latest" }
  - { name: "tflint", no-apt: true, no-apk: true, asdfVersion: "latest" }
  - name: "tmux"
  - name: "wget"
  - name: "yarn"
  - { name: "yq", no-apt: true, asdfVersion: "latest" }
  - name: "zsh"
asdf:
  plugins:
    - name: "datree"
      url: "https://github.com/webofmars/asdf-plugin-datree"
apt:
  repositories:
    - name: "microsoft"
      key: "https://packages.microsoft.com/keys/microsoft.asc"
      string: "deb https://packages.microsoft.com/ubuntu/$(lsb_release -rs)/prod $(lsb_release -cs) main"
    - name: "git-core-ubuntu-ppa"
      key: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xe1dd270288b4e6030699e45fa1715d88e1df1f24"
      string: "deb http://ppa.launchpad.net/git-core/ppa/ubuntu $(lsb_release -cs) main"
    - name: "helm-stable-debian"
      key: "https://baltocdn.com/helm/signing.asc"
      string: "deb https://baltocdn.com/helm/stable/debian all main"
    - name: "kubernetes"
      key: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
      string: "deb https://apt.kubernetes.io kubernetes-xenial main"
    - name: "kubic-libcontainers-stable"
      key: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_$(lsb_release -rs)/Release.key"
      string: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_$(lsb_release -rs)/ /"
    - name: "nodesource"
      key: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
      string: "deb https://deb.nodesource.com/node_18.x $(lsb_release -cs) main"
    - name: "yarn"
      key: "https://dl.yarnpkg.com/debian/pubkey.gpg"
      string: "deb https://dl.yarnpkg.com/debian/ stable main"

brew:
  taps:
    - name: "homebrew/autoupdate"
    - name: "homebrew/bundle"
    - name: "homebrew/cask"
    - name: "homebrew/cask-fonts"
    - name: "homebrew/cask-versions"
    - name: "homebrew/command-not-found"
    - name: "homebrew/core"
    - name: "datreeio/datree"
  casks:
    - name: "authy"
    - name: "brave-browser"
    - name: "calibre"
    - name: "cinebench"
    - name: "discord"
    - name: "dropbox"
    - name: "firefox"
    - name: "font-fira-code"
    - name: "geekbench"
    - name: "google-chrome"
    - name: "google-drive"
    - name: "gpg-suite"
    - name: "handbrake"
    - name: "iterm2"
    - name: "jetbrains-toolbox"
    - name: "lens"
    - name: "macfuse"
    - name: "microsoft-edge"
    - name: "private-internet-access"
    - name: "qbittorrent"
    - name: "rectangle"
    - name: "skype"
    - name: "spotify"
    - name: "teamviewer"
    - name: "telegram-desktop"
    - name: "tor-browser"
    - name: "visual-studio-code"
    - name: "vlc"
    - name: "xnviewmp"
    - name: "yandex-disk"
    - name: "zoom"
  apps:
    - name: "Brother iPrint&Scan"
      id: "1193539993"
    - name: "Disk Speed Test"
      id: "425264550"
    - name: "Grammarly for Safari"
      id: "1462114288"
    - name: "Messenger"
      id: "1480068668"
    - name: "Slack"
      id: "803453959"
    - name: "The Unarchiver"
      id: "425424353"
helm:
  plugins:
    - name: "helm-diff"
      url: "https://github.com/databus23/helm-diff"
    - name: "helm-secrets"
      url: "https://github.com/jkroepke/helm-secrets"
krew:
  plugins:
    - name: "access-matrix"
    - name: "datree"
    - name: "deprecations"
    - name: "get-all"
    - name: "konfig"
    - name: "modify-secret"
    - name: "neat"
    - name: "node-shell"
    - name: "resource-capacity"
    - name: "score"
    - name: "sniff"
    - name: "tree"
    - name: "tunnel"
    - name: "view-allocations"
    - name: "who-can"
