packages:
  - { name: "age" }
  - { name: "bat" }
  - { name: "bash" }
  - { name: "coreutils", test: "realpath --help" }
  - { name: "curl" }
  - { name: "colima", no-ubuntu: true, no-alpine: true, no-manjaro: true, toolchains: "docker, kubernetes" }
  - { name: "datree", no-ubuntu: true, no-alpine: true, asdfVersion: "latest", toolchains: "extra" }
  - { name: "delta", darwin: "git-delta", manjaro: "git-delta", no-ubuntu: true, asdfVersion: "latest" }
  - { name: "direnv", no-darwin: true, no-ubuntu: true, no-alpine: true, no-manjaro: true, asdfVersion: "latest" }
  - { name: "dive", no-ubuntu: true, no-alpine: true, no-manjaro: true, asdfVersion: "latest", toolchains: "docker, kubernetes" }
  - { name: "docker", ubuntu: "moby-cli", alpine: "docker-cli", toolchains: "docker" }
  - { name: "exa" }
  - { name: "fd", ubuntu: "fd-find" }
  - { name: "gh", no-ubuntu: true, alpine: "github-cli", manjaro: "github-cli", asdf: "github-cli", asdfVersion: "latest" }
  - { name: "git" }
  - { name: "gnupg", test: "gpg --help" }
  - { name: "helm", no-alpine: true, asdfVersion: "latest", toolchains: "kubernetes" }
  - { name: "htop" }
  - { name: "httpie", test: "http --version" }
  - {
      name: "java",
      no-darwin: true,
      no-ubuntu: true,
      alpine: "openjdk17-jdk",
      no-manjaro: true,
      asdfVersion: "latest:temurin-17",
      toolchains: "java",
    }
  - { name: "jq" }
  - { name: "k9s", no-ubuntu: true, no-alpine: true, asdfVersion: "latest", toolchains: "kubernetes" }
  - { name: "kubectl", no-alpine: true, asdfVersion: "latest", toolchains: "kubernetes" }
  - { name: "kubectx", no-ubuntu: true, asdfVersion: "latest", toolchains: "kubernetes" }
  - { name: "mas", no-ubuntu: true, no-alpine: true, no-manjaro: true, test: "mas" }
  - { name: "maven", no-darwin: true, no-ubuntu: true, no-manjaro: true, asdfVersion: "3.8.6", test: "mvn --help", toolchains: "java" }
  - { name: "neovim", test: "nvim --help" }
  - { name: "nodejs", no-darwin: true, no-manjaro: true, asdfVersion: "latest:18", test: "node --help", toolchains: "node" }
  - { name: "npm", no-darwin: true, no-ubuntu: true, no-manjaro: true, test: "npm -v", toolchains: "node" }
  - { name: "popeye", no-ubuntu: true, no-alpine: true, asdfVersion: "v0.10.1", toolchains: "extra" }
  - { name: "pre-commit", no-ubuntu: true, no-alpine: true, no-manjaro: true, asdfVersion: "latest" }
  - { name: "ripgrep", test: "rg --help" }
  - { name: "skopeo", toolchains: "docker, kubernetes" }
  - { name: "sops", no-ubuntu: true, no-alpine: true, asdfVersion: "latest", toolchains: "iac" }
  - { name: "stern", no-ubuntu: true, no-alpine: true, asdfVersion: "latest", toolchains: "extra" }
  - { name: "terraform", no-ubuntu: true, no-alpine: true, asdfVersion: "latest", toolchains: "iac" }
  - { name: "terragrunt", no-ubuntu: true, no-alpine: true, asdfVersion: "latest", toolchains: "iac" }
  - { name: "tflint", no-ubuntu: true, no-alpine: true, no-manjaro: true, asdfVersion: "latest", toolchains: "iac" }
  - { name: "tmux", test: "tmux -V" }
  - { name: "yarn", no-manjaro: true, asdfVersion: "latest", toolchains: "node" }
  - { name: "yq", no-ubuntu: true, asdfVersion: "latest", toolchains: "kubernetes" }
  - { name: "wget" }
  - { name: "zsh" }
helm:
  plugins:
    - name: "diff"
      url: "https://github.com/databus23/helm-diff"
    - name: "secrets"
      url: "https://github.com/jkroepke/helm-secrets"
krew:
  plugins:
    - { name: "access-matrix", linux_arm64: "no" }
    - { name: "datree", test: "version" }
    - { name: "deprecations", linux_arm64: "no" }
    - { name: "get-all", linux_arm64: "no" }
    - name: "konfig"
    - { name: "modify-secret", linux_arm64: "no" }
    - name: "neat"
    - { name: "node-shell", test: "-v" }
    - name: "resource-capacity"
    - name: "score"
    - { name: "sniff", alpine: "no", linux_arm64: "no" }
    - { name: "tree", linux_arm64: "no" }
    - name: "tunnel"
    - { name: "view-allocations", alpine: "no", linux_arm64: "no" }
    - name: "who-can"
