packages:
  - "bash"
  - "bat"
  - "colima [no-apt no-apk]"
  - "curl"
  - "datree [no-apt no-apk asdf::latest]"
  - "direnv [no-brew no-apt no-apk asdf::latest]"
  - "dive [no-apt no-apk asdf::latest]"
  - "docker [apt:docker-ce]"
  - "dockutil [no-apt no-apk]"
  - "dpkg"
  - "exa"
  - "fd [apt:fd-find]"
  - "gh [no-apt apk:github-cli asdf:github-cli:latest]"
  - "git"
  - "git-delta [no-apt apk:delta asdf:delta:latest]"
  - "gnupg"
  - "helm [no-apk asdf::latest]"
  - "htop"
  - "httpie"
  - "java [no-brew no-apt apk:openjdk17-jdk asdf::temurin-17.0.4+101]"
  - "jq"
  - "k9s [no-apt no-apk asdf::latest]"
  - "kubectl [no-apk asdf::latest]"
  - "kubectx [no-apt asdf::latest]"
  - "mas [no-apt no-apk]"
  - "maven [no-brew no-apt asdf::latest]"
  - "neovim"
  - "nodejs [brew:node@16]"
  - "npm [no-brew no-apt]"
  - "pre-commit [no-apt no-apk asdf::latest]"
  - "ripgrep"
  - "skopeo"
  - "sops [no-apt no-apk asdf::latest]"
  - "terraform [no-apt no-apk asdf::latest]"
  - "terragrunt [no-apt no-apk asdf::latest]"
  - "tflint [no-apt no-apk asdf::latest]"
  - "tmux"
  - "wget"
  - "yarn"
  - "yq [no-apt asdf::latest]"
  - "zsh"
asdf:
  plugins:
    - "https://github.com/webofmars/asdf-plugin-datree"
apt:
  repositories:
    - name: "azure-cli"
      key: "https://packages.microsoft.com/keys/microsoft.asc"
      string: "deb https://packages.microsoft.com/repos/azure-cli $(lsb_release -cs) main"
    - name: "docker"
      key: "https://download.docker.com/linux/ubuntu/gpg"
      string: "deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - name: "git-core-ubuntu-ppa"
      key: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xe1dd270288b4e6030699e45fa1715d88e1df1f24"
      string: "deb http://ppa.launchpad.net/git-core/ppa/ubuntu $(lsb_release -cs) main"
    - name: "helm-stable-debian"
      key: "https://baltocdn.com/helm/signing.asc"
      string: "deb https://baltocdn.com/helm/stable/debian all main"
    - name: "kubernetes"
      key: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
      string: "deb https://apt.kubernetes.io kubernetes-xenial main"
    - name: "kubic-libcontainers-stable"
      key: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_$(lsb_release -rs)/Release.key"
      string: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_$(lsb_release -rs)/ /"
    - name: "nodesource"
      key: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
      string: "deb https://deb.nodesource.com/node_16.x $(lsb_release -cs) main"
    - name: "yarn"
      key: "https://dl.yarnpkg.com/debian/pubkey.gpg"
      string: "deb https://dl.yarnpkg.com/debian/ stable main"

brew:
  taps:
    - "homebrew/autoupdate"
    - "homebrew/bundle"
    - "homebrew/cask"
    - "homebrew/cask-fonts"
    - "homebrew/cask-versions"
    - "homebrew/command-not-found"
    - "homebrew/core"
    - "datreeio/datree"
  casks:
    - "authy"
    - "calibre"
    - "cinebench"
    - "dropbox"
    - "firefox"
    - "font-fira-code"
    - "geekbench"
    - "google-chrome"
    - "google-drive"
    - "gpg-suite"
    - "handbrake"
    - "iterm2"
    - "jetbrains-toolbox"
    - "lens"
    - "macfuse"
    - "microsoft-edge"
    - "private-internet-access"
    - "qbittorrent"
    - "skype"
    - "spotify"
    - "teamviewer"
    - "telegram-desktop"
    - "tor-browser"
    - "visual-studio-code"
    - "vlc"
    - "xnviewmp"
    - "yandex-disk"
    - "zoom"
  apps:
    - name: "Brother iPrint&Scan"
      id: "1193539993"
    - name: "Disk Speed Test"
      id: "425264550"
    - name: "Grammarly for Safari"
      id: "1462114288"
    - name: "Messenger"
      id: "1480068668"
    - name: "Slack"
      id: "803453959"
    - name: "The Unarchiver"
      id: "425424353"
helm:
  plugins:
    - https://github.com/databus23/helm-diff
    - https://github.com/aslafy-z/helm-git
    - https://github.com/jkroepke/helm-secrets
krew:
  plugins:
    - access-matrix
    - datree
    - deprecations
    - get-all
    - konfig
    - modify-secret
    - neat
    - node-shell
    - popeye
    - resource-capacity
    - score
    - sniff
    - stern
    - tap
    - tree
    - tunnel
    - view-allocations
    - view-secret
    - who-can
