plugin:
  # Annotate each line in the given resource's YAML with information from the managedFields to show who last modified the field.
  blame:
    shortCut: b
    confirm: false
    description: Blame
    scopes:
    - all
    command: sh
    background: false
    args:
    - -c
    - kubectl-blame $RESOURCE_NAME $NAME -n $NAMESPACE --context $CONTEXT | less
  # Dive into image layers
  dive:
    shortCut: d
    confirm: false
    description: Dive image
    scopes:
    - containers
    command: dive
    background: false
    args:
    - $COL-IMAGE
  # Get all resources in a namespace using the krew get-all plugin
  get-all-namespace:
    shortCut: g
    confirm: false
    description: get-all
    scopes:
    - namespaces
    command: sh
    background: false
    args:
    - -c
    - kubectl get-all --context $CONTEXT -n $NAME | less -K
  get-all-other:
    shortCut: g
    confirm: false
    description: get-all
    scopes:
    - all
    command: sh
    background: false
    args:
    - -c
    - kubectl get-all --context $CONTEXT -n $NAMESPACE | less -K
  # Edit Secret
  edit-secret:
    shortCut: Ctrl-X
    confirm: false
    description: Edit Decoded Secret
    scopes:
    - secrets
    command: kubectl
    background: false
    args:
    - modify-secret
    - --namespace
    - $NAMESPACE
    - --context
    - $CONTEXT
    - $NAME
  # Leverage stern (https://github.com/stern/stern) to output logs.
  stern:
    shortCut: Ctrl-L
    confirm: false
    description: Logs <Stern>
    scopes:
    - pods
    command: stern
    background: false
    args:
    - --tail
    - 50
    - $FILTER
    - -n
    - $NAMESPACE
    - --context
    - $CONTEXT
  # Removes all finalizers from the selected resource.
  remove_finalizers:
    shortCut: Ctrl-F
    confirm: true
    scopes:
    - all
    description: |
      Removes all finalizers from selected resource. Be careful when using it,
      it may leave dangling resources or delete them
    command: kubectl
    background: true
    args:
    - patch
    - --context
    - $CONTEXT
    - --namespace
    - $NAMESPACE
    - $RESOURCE_NAME
    - $NAME
    - -p
    - '{"metadata":{"finalizers":null}}'
    - --type
    - merge
  # remove finalizers from a stuck namespace
  rm-ns:
    shortCut: n
    confirm: true
    description: Remove NS Finalizers
    scopes:
    - namespace
    command: sh
    background: false
    args:
    - -c
    - kubectl get namespace $NAME -o json | jq '.spec.finalizers=[]' | kubectl replace --raw /api/v1/namespaces/$NAME/finalize -f - > /dev/null
  # watch events on selected resources
  # requires linux "watch" command
  # change '-n' to adjust refresh time in seconds
  watch-events:
    shortCut: Shift-E
    confirm: false
    description: Get Events
    scopes:
    - all
    command: sh
    background: false
    args:
    - -c
    - watch -n 5 kubectl get events --context $CONTEXT --namespace $NAMESPACE --field-selector involvedObject.name=$NAME
