[packages]
common = [
  "age",
  "bash",
  "bat",
  "broot",
  "btop",
  "coreutils",
  "croc",
  "curl",
  "direnv",
  "duf",
  "dust",
  "eza",
  "fd",
  "gh",
  "git",
  "git-delta",
  "gnupg",
  "gocryptfs",
  "httpie",
  "hyperfine",
  "jq",
  "neovim",
  "procs",
  "qrencode",
  "rclone",
  "ripgrep",
  "sd",
  "tokei",
  "tmux",
  "unison",
  "wget",
  "zbar",
  "zsh"
]
