[packages.base.docker]
dive = {manager = "mise", package = "github:wagoodman/dive", policy = {allow = [
  "dive *"
]}}
docker-buildx = {version = "docker buildx version", policy = {allow = [
  "docker buildx version *"
], ask = [
  "docker buildx *"
]}}
lazydocker = {manager = "mise", package = "aqua:jesseduffield/lazydocker", policy = {ask = [
  "lazydocker *"
]}}

[packages.base.docker.docker]
completion = true

[packages.base.docker.docker.policy]
allow = [
  "docker images *",
  "docker info *",
  "docker logs *",
  "docker ps *",
  "docker version *"
]
ask = [
  "docker build *",
  "docker compose *",
  "docker cp *",
  "docker exec *",
  "docker pull *",
  "docker run *"
]
deny = [
  "docker * run * --mount type=bind,source=/*",
  "docker * run * --privileged *",
  "docker * run * --volume /:*",
  "docker * run * -v /:*",
  "docker * system prune *",
  "docker compose down *",
  "docker compose rm *",
  "docker container rm *",
  "docker image rm *",
  "docker rm *",
  "docker rmi *",
  "docker volume rm *"
]

[packages.base.docker.docker-compose]
version = "docker compose version"

[packages.base.docker.docker-compose.policy]
allow = [
  "docker compose config *",
  "docker compose logs *",
  "docker compose ps *"
]
ask = [
  "docker compose build *",
  "docker compose exec *",
  "docker compose pull *",
  "docker compose run *",
  "docker compose up *"
]
deny = ["docker compose down *", "docker compose rm *"]
