[packages.base.iac]
sops = {manager = "mise", policy = {ask = ["sops *"]}}

[packages.base.iac.opentofu]
manager = "mise"
package = "aqua:opentofu/opentofu"
bin = "tofu"
version = "tofu version"

[packages.base.iac.opentofu.policy]
allow = ["tofu output *", "tofu plan *", "tofu show *", "tofu version *"]
ask = ["tofu *"]
deny = [
  "tofu * apply *",
  "tofu * destroy *",
  "tofu * import *",
  "tofu * state rm *",
  "tofu * workspace delete *"
]

[packages.base.iac.terragrunt]
manager = "mise"
completion = {repo = "thuandt/zsh-terraform@master", path = "_terragrunt"}

[packages.base.iac.terragrunt.policy]
allow = [
  "terragrunt output *",
  "terragrunt plan *",
  "terragrunt show *",
  "terragrunt version *"
]
ask = ["terragrunt *"]
deny = [
  "terragrunt * apply *",
  "terragrunt * destroy *",
  "terragrunt * import *",
  "terragrunt * state rm *"
]
