[packages.base.iac]
sops = {completion = true, manager = "mise"}

[packages.base.iac.opentofu]
manager = "mise"
package = "aqua:opentofu/opentofu"
bin = "tofu"
version = "tofu version"

[packages.base.iac.opentofu.policy]
allow = [
  "tofu fmt -check *",
  "tofu output *",
  "tofu plan *",
  "tofu providers *",
  "tofu show *",
  "tofu validate *",
  "tofu version *",
  "tofu workspace list *",
  "tofu workspace show *"
]
deny = [
  "tofu * apply *",
  "tofu * destroy *",
  "tofu * force-unlock *",
  "tofu * import *",
  "tofu * login *",
  "tofu * state rm *",
  "tofu * workspace delete *",
  "tofu apply *",
  "tofu destroy *",
  "tofu force-unlock *",
  "tofu import *",
  "tofu login *"
]

[packages.base.iac.terragrunt]
manager = "mise"

[packages.base.iac.terragrunt.policy]
allow = [
  "terragrunt output *",
  "terragrunt plan *",
  "terragrunt show *",
  "terragrunt validate *",
  "terragrunt version *",
  "terragrunt workspace list *",
  "terragrunt workspace show *"
]
deny = [
  "terragrunt * apply *",
  "terragrunt * destroy *",
  "terragrunt * force-unlock *",
  "terragrunt * import *",
  "terragrunt * state rm *",
  "terragrunt apply *",
  "terragrunt destroy *",
  "terragrunt force-unlock *",
  "terragrunt import *"
]
