[packages.base.java]
java = {manager = "mise", version = "java -version", pin = "lts", policy = {allow = [
  "java -version"
]}}
maven = {manager = "mise", bin = "mvn", version = "mvn -v", policy = {allow = [
  "mvn -v",
  "mvn dependency:tree *",
  "mvn help:effective-pom *"
]}}
