[packages.ubuntu.core]
chezmoi = {manager = "mise"}
fd = {name = "fd-find"}
"git-delta" = {manager = "mise", name = "delta"}
pcscd = {name = "pcscd"}

[packages.ubuntu.docker]
docker = {name = "docker-ce"}
"docker-buildx" = {name = "docker-buildx-plugin"}
"docker-compose" = {name = "docker-compose-plugin"}

[packages.ubuntu.kubernetes]
"kubectl-access-matrix" = {exclude_arch = ["arm64"]}
"kubectl-tree" = {exclude_arch = ["arm64"]}
oc = {exclude_arch = ["arm64"]}
