[packages.os.ubuntu.core]
bubblewrap = {disabled = ["ephemeral"], bin = "bwrap"}
chezmoi = {manager = "mise"}
fd = {package = "fd-find"}
"git-delta" = {manager = "mise", package = "delta"}
pcscd = {package = "pcscd"}
socat = {disabled = ["ephemeral"], version = "socat -V"}

[packages.os.ubuntu.docker]
docker = {package = "docker-ce"}
"docker-buildx" = {package = "docker-buildx-plugin"}
"docker-compose" = {package = "docker-compose-plugin"}

[packages.os.ubuntu.kubernetes]
"kubectl-access-matrix" = {exclude_arch = ["arm64"]}
"kubectl-tree" = {exclude_arch = ["arm64"]}
oc = {exclude_arch = ["arm64"]}
