name: CI Docker
on:
  workflow_call:
    inputs:
      matrix:
        type: string
        default: '["archlinux","fedora","ubuntu"]'
  schedule:
    - cron: 0 23 * * 6
  workflow_dispatch:
    inputs:
      publish:
        description: Publish docker images
        required: true
        default: false
        type: boolean
concurrency:
  group: ci-docker-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  docker-build:
    strategy:
      matrix:
        os: ${{ fromJSON(inputs.matrix || '["archlinux","fedora","ubuntu"]') }}
      fail-fast: false
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: docker/github-builder/.github/workflows/build.yml@c2782c55efa56a01b9c30021db8f5ec3993228a3 # v1.8.0
    with:
      output: image
      push: ${{ (github.event_name == 'push' && github.ref_name == 'main') || github.event_name == 'schedule' || inputs.publish == true }}
      context: .
      file: containers/${{ matrix.os }}/Dockerfile
      platforms: linux/arm64,linux/amd64
      cache: true
      sbom: true
      meta-images: |
        ghcr.io/${{ github.repository }}
        docker.io/${{ github.repository }}
      meta-tags: |
        type=schedule,prefix=${{ matrix.os }}-,pattern={{date 'YYYYMMDD'}}
        type=raw,value=${{ matrix.os }},enable={{is_default_branch}}
        type=ref,event=pr,prefix=${{ matrix.os }}-pr-
      meta-flavor: |
        latest=${{ github.ref_name == 'main' && contains(matrix.os, 'ubuntu') }}
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        - registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
