name: CI

on:
  push:
  pull_request:

jobs:
  clone-and-install:
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: ./install.sh
  docker-build:
    runs-on: ubuntu-latest
    concurrency:
      group: docker-build-${{ github.head_ref }}
      cancel-in-progress: true
    steps:
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: |
            adyranov/dotfiles:latest
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
      - name: Move Docker Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
