name: Update copyright year(s) in license file

on:
  schedule:
    - cron: "0 3 1 1 *" # 03:00 AM on January 1

jobs:
  update-license-year:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@00b7495233bb4a9229204b2bd3e2a6df7551e155 # v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
