name: Update copyright year(s) in license file

on:
  schedule:
  - cron: 0 3 1 1 *     # 03:00 AM on January 1

jobs:
  update-license-year:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: 0
    - uses: FantasticFiasco/action-update-license-year@9135da8f9ccc675217e02357c744b6b541d45cb0   # v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
