name: Update copyright year(s) in license file

on:
  schedule:
    - cron: "0 3 1 1 *" # 03:00 AM on January 1

jobs:
  update-license-year:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@26ffac173f956c25f7467aa8e6f750eed24a1b7a # v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
