name: Update copyright year(s) in license file
on:
  schedule:
    - cron: 0 3 1 1 * # 03:00 AM on January 1
jobs:
  update-license-year:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@f180e962fa988db222d8f03ef4636750312d1b3d # v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
