[packages.fedora.core]
fd = {name = "fd-find"}
openssh-client = {name = "openssh-clients"}
"pcsc-lite" = {name = "pcsc-lite"}

[packages.fedora.docker]
docker = {name = "docker-ce"}
"docker-buildx" = {name = "docker-buildx-plugin"}
"docker-compose" = {name = "docker-compose-plugin"}
