[packages.fedora.core]
bubblewrap = {disabled = "ephemeral", bin = "bwrap"}
difftastic = {manager = "system"}
fd = {package = "fd-find"}
openssh-client = {package = "openssh-clients"}
"pcsc-lite" = {package = "pcsc-lite", test = "rpm -q pcsc-lite"}
socat = {disabled = "ephemeral", version = "socat -V"}

[packages.fedora.docker]
docker = {package = "docker-ce"}
"docker-buildx" = {package = "docker-buildx-plugin"}
"docker-compose" = {package = "docker-compose-plugin"}
