[repositories.fedora.cloud.microsoft-azure-cli]
baseurl = "https://packages.microsoft.com/yumrepos/azure-cli"
gpgkey = "https://packages.microsoft.com/keys/microsoft.asc"
repo_id = "azure-cli"

[repositories.fedora.docker.docker-ce]
repo_url = "https://download.docker.com/linux/fedora/docker-ce.repo"
